'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShopBridgeItem
    Public Property ItemID As Integer
    Public Property ItemName As String
    Public Property ItemDesc As String
    Public Property ItemPrice As Nullable(Of Decimal)

End Class
